### ISSUE TITLE
.deb soon?

### ISSUE THREAD

**Issue by forteller** [plexydesk/plexydesk#48]
Hi. This looks great, and from the website it seems like you want it to be clean and simple for anyone to use. But if there is no easy way to install it, very few non-technical people will even try it. I'm hoping for a .deb soon. Thanks!

**Comment by siraj** [comment]
Hi @forteller 

Just busy making it feature complete these days :). we have bunch of build files for creating deb's and RPM's it needs to be updated to compile major changes we made.

**Comment by siraj** [comment]
@forteller there it is!, thanks for filing the issue :+1:

**Comment by forteller** [comment]
Sounds promising, but I don't really understand. I thought you ment that the .deb is available, but when I go to http://www.plexydesk.org/download/ and click on the big, green "get now" button I'm sent to a new page where I have to click on yet another button (three clicks now) to download, and it tells me it's only available for Mac OS (in the dropdown. in system requirements at the bottom of the page it says Mac or Windows)?

Sorry if I'm being stupid, but I'm not really a very technical person and things needs to be simple for me to understand how to do it. And that's the same for most people, I think :)

**Comment by siraj** [comment]
@forteller  Hi, 

No problem, feel free to ask technical or non-technical questions here :). The debian files were added to make plexydesk binaries possible on platforms which supports debian files. At the moment we are trying to make binaries available using ubuntu launchpad, unfortunately due to some technical limitations we were not able to make the binaries available to download for Linux. but stay subscribed to his issue, and I'll notify you as soon as the binaries are available for download. 

Thank you.

**Comment by siraj** [comment]
@forteller experimental packages are available for Ubuntu https://launchpad.net/~sirajrazick/+archive/ubuntu/plexydesk

**Comment by siraj** [comment]
we have ready to install binaries for all the recent versions of Ubuntu. You can get it from https://launchpad.net/~plexydesk/+archive/ubuntu/plexydesk.

If you want to build packages for a different variant of Debian, simply run dist/make_deb.sh with the required arguments. 

Thank you, and I'm closing this issue now.
